name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: recursive
        fetch-depth: 0 # needed for versioning
    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Gradle
      run: ./gradlew clean build test
    - uses: actions/upload-artifact@v2-preview
      with:
        name: artifact
        path: build/libs/*
